import type { DesignSystem, NavItem, GhostThemeMeta, CustomThemeSetting, RoutingConfig } from './store';
import { serializeGhostFilter } from './ghost-filter';

interface PuckComponent {
  type: string;
  props: Record<string, unknown>;
}

interface PuckContent {
  content: PuckComponent[];
  root?: { props?: Record<string, unknown> };
  zones?: Record<string, PuckComponent[]>;
}

interface PageInput {
  name: string;
  slug: string;
  type: string;
  isHomepage: boolean;
  isCollection: boolean;
  collectionFilter: string;
  content: PuckContent;
}

interface ProjectInput {
  name: string;
  slug: string;
  designSystem: DesignSystem;
  navigation: NavItem[];
  themeSettings: Record<string, unknown>;
  customSettings: CustomThemeSetting[];
  routing: RoutingConfig;
  pages: PageInput[];
}

interface ThemeFile {
  path: string;
  content: string;
}

// ===== SUB-COMPILERS =====

function compilePackageJson(project: ProjectInput): string {
  const custom: Record<string, any> = {};
  for (const setting of project.customSettings) {
    custom[setting.key] = {
      type: setting.type,
      default: setting.default,
    };
    if (setting.options?.length && setting.type === 'select') {
      custom[setting.key].options = setting.options;
    }
    if (setting.group) {
      custom[setting.key].group = setting.group;
    }
  }

  return JSON.stringify({
    name: project.slug,
    description: `Ghost theme: ${project.name}`,
    version: "1.0.0",
    engines: { ghost: ">=5.0.0" },
    license: "MIT",
    author: { name: "Ghost Theme Builder" },
    config: {
      posts_per_page: (project.themeSettings?.postsPerPage as number) || 10,
      card_assets: true,
      custom,
    },
    keywords: ["ghost-theme"],
  }, null, 2);
}

function compileRoutesYaml(project: ProjectInput): string | null {
  const collections = project.routing?.collections || [];
  const taxonomies = project.routing?.taxonomies || { tag: '/tag/{slug}/', author: '/author/{slug}/' };

  // Only emit routes.yaml if there are custom collections
  if (collections.length === 0) return null;

  let yaml = `routes:\n  /: home\n\ncollections:\n`;
  for (const col of collections) {
    yaml += `  ${col.path}:\n`;
    yaml += `    permalink: ${col.permalink}\n`;
    yaml += `    template: ${col.template}\n`;
    if (col.filter) {
      yaml += `    filter: ${col.filter}\n`;
    }
  }

  yaml += `\ntaxonomies:\n`;
  yaml += `  tag: ${taxonomies.tag}\n`;
  yaml += `  author: ${taxonomies.author}\n`;

  return yaml;
}

function resolveStyleToken(value: string | undefined, tokenPath: string, ds: DesignSystem): string {
  if (!value) return '';
  const isEditable = ds.editableTokens?.includes(tokenPath);
  if (isEditable) {
    const key = tokenPath.replace('.', '_');
    return `var(--ghost-custom-${key}, ${value})`; // Fallback to value if custom var is missing
  }
  return value;
}

function compileCSS(ds: DesignSystem): string {
  let customVars = '';
  if (ds.editableTokens) {
    for (const token of ds.editableTokens) {
      const key = token.replace('.', '_');
      customVars += `  --ghost-custom-${key}: {{@custom.${key}}};\n`;
    }
  }

  return `/* Ghost Theme CSS - Generated by Ghost Theme Builder */
@import url('https://fonts.googleapis.com/css2?family=${ds.typography.headingFont.replace(/ /g, "+")}:wght@400;500;600;700;800&family=${ds.typography.bodyFont.replace(/ /g, "+")}:wght@300;400;500;600&display=swap');

:root {
  --color-primary: ${ds.colors.primary};
  --color-secondary: ${ds.colors.secondary};
  --color-accent: ${ds.colors.accent};
  --color-bg: ${ds.colors.background};
  --color-surface: ${ds.colors.surface};
  --color-text: ${ds.colors.text};
  --color-text-muted: ${ds.colors.textMuted};
  --color-border: ${ds.colors.border};
  --font-heading: '${ds.typography.headingFont}', sans-serif;
  --font-body: '${ds.typography.bodyFont}', sans-serif;
  --radius: ${ds.borderRadius};
${customVars}
}
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; -webkit-font-smoothing: antialiased; }
body { font-family: var(--font-body); color: var(--color-text); background: var(--color-bg); line-height: 1.6; }
img { max-width: 100%; height: auto; }
a { color: var(--color-primary); text-decoration: none; }
a:hover { text-decoration: underline; }
.container { max-width: ${ds.spacing.containerMaxWidth}; margin: 0 auto; padding: 0 24px; }
h1, h2, h3, h4, h5, h6 { font-family: var(--font-heading); line-height: 1.2; }
h1 { font-size: ${ds.typography.h1Size}; }
h2 { font-size: ${ds.typography.h2Size}; }
h3 { font-size: ${ds.typography.h3Size}; }
h4 { font-size: ${ds.typography.h4Size}; }
.btn-primary { display: inline-flex; align-items: center; justify-content: center; padding: 12px 24px; background: var(--color-primary); color: white; border-radius: var(--radius); font-weight: 600; text-decoration: none; transition: opacity 0.2s; }
.btn-primary:hover { opacity: 0.9; text-decoration: none; }
.post-feed { display: grid; gap: 24px; }
.post-card { border-radius: var(--radius); overflow: hidden; border: 1px solid var(--color-border); transition: box-shadow 0.2s; }
.post-card:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
.post-card-image { width: 100%; height: 200px; object-fit: cover; }
.post-card-content { padding: 20px; }
.site-header { display: flex; align-items: center; justify-content: space-between; padding: 16px 32px; border-bottom: 1px solid var(--color-border); }
.site-footer { padding: 48px 32px; text-align: center; background: var(--color-surface); }
.nav-list { display: flex; gap: 24px; list-style: none; }
.nav-list a { color: var(--color-text-muted); font-size: 14px; font-weight: 500; }
.nav-list a:hover { color: var(--color-text); }
.tag-pill { padding: 4px 12px; background: #e0e7ff; color: #4f46e5; border-radius: 100px; font-size: 12px; font-weight: 600; text-decoration: none; }
.tag-pill:hover { background: #c7d2fe; text-decoration: none; }
@media (max-width: 768px) {
  .post-feed { grid-template-columns: 1fr !important; }
  .grid { grid-template-columns: 1fr !important; }
  h1 { font-size: 32px; }
  .hero { min-height: 400px !important; }
}
.header-left { display: flex; align-items: center; gap: 16px; }
.header-right { display: flex; align-items: center; gap: 16px; }`;
}

// ===== COMPONENT RENDERERS =====

function renderComponentHbs(comp: PuckComponent, zones?: Record<string, PuckComponent[]>): string {
  const p = comp.props;
  switch (comp.type) {
    case "Hero": {
      const children = zones?.[`${comp.props.id}:hero-content`] || [];
      const inner = children.map(c => renderComponentHbs(c, zones)).join("\n");
      return `<section class="hero" style="min-height:${p.minHeight || "500px"};background-color:${p.backgroundColor || "#0f172a"};${p.backgroundImage ? `background-image:url(${p.backgroundImage});background-size:cover;background-position:center;` : ""}display:flex;align-items:center;justify-content:center;padding:60px 24px;width:100%">
  <div class="hero-content" style="max-width:800px;width:100%;display:flex;flex-direction:column;align-items:center;text-align:center;gap:16px">
    ${inner}
  </div>
</section>`;
    }

    case "Section": {
      const children = zones?.[`${comp.props.id}:content`] || [];
      const inner = children.map(c => renderComponentHbs(c, zones)).join("\n");
      return `<section style="background-color:${p.backgroundColor || "transparent"};padding:${p.paddingY || "60px"} ${p.paddingX || "24px"};width:100%">
${inner}
</section>`;
    }

    case "Container": {
      const children = zones?.[`${comp.props.id}:content`] || [];
      const inner = children.map(c => renderComponentHbs(c, zones)).join("\n");
      return `<div class="container" style="max-width:${p.maxWidth || "1200px"};margin:0 auto;width:100%">
${inner}
</div>`;
    }

    case "Grid": {
      const children = zones?.[`${comp.props.id}:content`] || [];
      const inner = children.map(c => renderComponentHbs(c, zones)).join("\n");
      return `<div class="grid" style="display:grid;grid-template-columns:repeat(${p.columns || "3"},1fr);gap:${p.gap || "24px"};width:100%">
${inner}
</div>`;
    }

    case "Heading":
      return `<${p.level || "h2"} style="color:${p.color || "#1e293b"};${p.fontSize ? `font-size:${p.fontSize};` : ""}font-weight:${p.fontWeight || "700"};text-align:${p.textAlign || "left"};line-height:1.2">${p.text || "Heading"}</${p.level || "h2"}>`;

    case "Paragraph":
      return `<p style="color:${p.color || "#475569"};font-size:${p.fontSize || "16px"};text-align:${p.textAlign || "left"};line-height:${p.lineHeight || "1.7"};max-width:720px">${p.text || ""}</p>`;

    case "Image":
      return `<img src="${p.src || "{{@site.cover_image}}"}" alt="${p.alt || ""}" style="width:${p.width || "100%"};height:${p.height || "auto"};border-radius:${p.borderRadius || "8px"};object-fit:${p.objectFit || "cover"};display:block" />`;

    case "Button":
      return `<a href="${p.url || "#"}" class="btn btn-${p.variant || "primary"} btn-${p.size || "md"}" style="border-radius:${p.borderRadius || "8px"}">${p.text || "Button"}</a>`;

    case "Card": {
      const children = zones?.[`${comp.props.id}:card-content`] || [];
      const inner = children.map(c => renderComponentHbs(c, zones)).join("\n");
      return `<div class="card" style="background-color:${p.backgroundColor || "#ffffff"};border-radius:${p.borderRadius || "12px"};padding:${p.padding || "24px"};overflow:hidden;border:1px solid #e2e8f0">
  ${inner}
</div>`;
    }

    case "Divider":
      return `<hr style="border:none;border-top:${p.thickness || "1px"} ${p.style || "solid"} ${p.color || "#e2e8f0"};margin:${p.margin || "32px"} 0" />`;

    case "Spacer":
      return `<div style="height:${p.height || "40px"}"></div>`;

    case "Header": {
      const left = zones?.[`${comp.props.id}:header-left`] || [];
      const right = zones?.[`${comp.props.id}:header-right`] || [];
      return `<header class="site-header" style="background-color:${p.backgroundColor || "#ffffff"}">
  <div class="header-left">${left.map(c => renderComponentHbs(c, zones)).join("\n")}</div>
  <div class="header-right">${right.map(c => renderComponentHbs(c, zones)).join("\n")}</div>
</header>`;
    }

    case "Footer": {
      const children = zones?.[`${comp.props.id}:footer-content`] || [];
      return `<footer class="site-footer" style="background-color:${p.backgroundColor || "#0f172a"}">
  ${children.map(c => renderComponentHbs(c, zones)).join("\n")}
</footer>`;
    }

    // --- Ghost Dynamic ---
    case "GhostSiteTitle":
      return `<h1 class="site-title" style="color:${p.color || "#1e293b"};font-size:${p.fontSize || "24px"};font-weight:${p.fontWeight || "800"};margin:0;line-height:1.2"><a href="{{@site.url}}" style="color:inherit;text-decoration:none">{{@site.title}}</a></h1>`;

    case "GhostSiteDescription":
      return `<p class="site-description" style="color:${p.color || "#64748b"};font-size:${p.fontSize || "16px"};margin:0">{{@site.description}}</p>`;

    case "GhostSiteLogo":
      return `{{#if @site.logo}}<a href="{{@site.url}}"><img src="{{@site.logo}}" alt="{{@site.title}}" style="height:${p.height || "40px"};display:block" /></a>{{else}}<h2 style="font-size:24px;font-weight:700;margin:0"><a href="{{@site.url}}" style="text-decoration:none;color:inherit">{{@site.title}}</a></h2>{{/if}}`;

    case "GhostNavigation":
      return `{{navigation${p.isSecondary ? ' type="secondary"' : ''}}}`;

    case "GhostPostFeed": {
      const filterObj: Record<string, any> = {};
      if (p.tags) filterObj.tag = (p.tags as string).split(',').map(t => t.trim());
      if (p.featuredOnly) filterObj.featured = true;
      if (p.excludeId) filterObj.excludeId = true;
      const filterStr = serializeGhostFilter(filterObj);
      
      const limitStr = p.limit || "6";
      
      return `<div class="post-feed" style="display:grid;grid-template-columns:repeat(${p.postsPerRow || "3"},1fr);gap:24px">
  {{#get "posts" limit="${limitStr}"${filterStr ? ` filter="${filterStr}"` : ""}}}
    {{#foreach posts}}
      {{> "post-card"}}
    {{/foreach}}
  {{else}}
    <p>No posts found.</p>
  {{/get}}
</div>`;
    }

    case "GhostAuthor":
      return `{{#author}}
<div class="author-profile" style="text-align:center;padding:24px;border:1px solid #e2e8f0;border-radius:8px">
  {{#if profile_image}}<img src="{{profile_image}}" alt="{{name}}" style="width:80px;height:80px;border-radius:50%;margin:0 auto 16px" />{{/if}}
  <h3 style="font-size:18px;font-weight:700;margin:0 0 8px 0">{{name}}</h3>
  {{#if bio}}<p style="font-size:14px;color:#64748b;max-width:300px;margin:0 auto">{{bio}}</p>{{/if}}
</div>
{{/author}}`;

    case "GhostTags":
      return `<div class="tags" style="display:flex;gap:8px;flex-wrap:wrap">
  {{tags separator="" autolink="true" class="tag-pill"}}
</div>`;

    case "GhostPagination":
      return `<div class="pagination" style="display:flex;justify-content:center;padding:32px 0">
  {{pagination}}
</div>`;

    case "GhostSubscribe":
      return `<div class="subscribe-section" style="padding:24px;border:1px solid #e2e8f0;border-radius:8px;background:#f8fafc">
  <form data-members-form="subscribe" style="display:flex;gap:8px">
    <input data-members-email type="email" required placeholder="Your email address" style="padding:10px 16px;border:1px solid #cbd5e1;border-radius:6px;width:100%;max-width:240px" />
    <button type="submit" style="padding:10px 20px;background:${p.buttonColor || "#4f46e5"};color:white;border:none;border-radius:6px;font-weight:600;cursor:pointer">Subscribe</button>
  </form>
</div>`;

    case "GhostPostContent":
      return `<div class="post-content">
  {{content}}
</div>`;

    case "GhostPostTitle":
      return `<h1 style="color:${p.color || "#1e293b"};font-size:${p.fontSize || "36px"};font-weight:${p.fontWeight || "800"};margin:0;line-height:1.2">{{title}}</h1>`;

    case "GhostPostDate":
      return `<span style="color:${p.color || "#64748b"};font-size:${p.fontSize || "14px"}">{{date format="MMMM DD, YYYY"}}</span>`;

    case "GhostPostFeatureImage":
      return `{{#if feature_image}}
<img src="{{feature_image}}" alt="{{title}}" style="width:100%;height:auto;border-radius:${p.borderRadius || "8px"};display:block" />
{{/if}}`;

    default:
      return `<!-- Unknown component: ${comp.type} -->`;
  }
}

// ===== MAIN COMPILER =====

export function compileTheme(project: ProjectInput): ThemeFile[] {
  const files: ThemeFile[] = [];
  const ds = project.designSystem;

  // 1. package.json
  files.push({
    path: "package.json",
    content: compilePackageJson(project),
  });

  // 2. routes.yaml
  const routesYaml = compileRoutesYaml(project);
  if (routesYaml) {
    files.push({ path: "routes.yaml", content: routesYaml });
  }

  // 3. CSS
  const css = compileCSS(ds);
  files.push({ path: "assets/css/theme.css", content: css });

  // 4. JS
  files.push({ path: "assets/js/theme.js", content: generateJS() });

  // 5. default.hbs
  files.push({ path: "default.hbs", content: generateDefaultHbs(project) });

  // 6. Partials
  files.push({ path: "partials/header.hbs", content: generateHeaderPartial(project) });
  files.push({ path: "partials/footer.hbs", content: generateFooterPartial(project) });
  files.push({ path: "partials/navigation.hbs", content: generateNavigationPartial() });
  files.push({ path: "partials/post-card.hbs", content: generatePostCardPartial() });

  // 7. Page templates
  for (const page of project.pages) {
    const { path, content } = generatePageTemplate(page, project);
    files.push({ path, content });
  }

  // 8. Required Ghost templates (if not already created)
  const existingPaths = new Set(files.map(f => f.path));
  if (!existingPaths.has("index.hbs")) {
    files.push({ path: "index.hbs", content: generateIndexFallback() });
  }
  if (!existingPaths.has("post.hbs")) {
    files.push({ path: "post.hbs", content: generatePostTemplate() });
  }
  if (!existingPaths.has("page.hbs")) {
    files.push({ path: "page.hbs", content: generateGenericPageTemplate() });
  }
  files.push({ path: "tag.hbs", content: generateTagTemplate() });
  files.push({ path: "author.hbs", content: generateAuthorTemplate() });
  files.push({ path: "error.hbs", content: generateErrorTemplate() });

  return files;
}

function renderPageContent(page: PageInput): string {
  const content = page.content as PuckContent;
  if (!content?.content?.length) return "<p>This page is empty.</p>";
  return content.content.map(c => renderComponentHbs(c, content.zones)).join("\n\n");
}

function generateDefaultHbs(project: ProjectInput): string {
  let customStyleBlock = '';
  if (project.designSystem.editableTokens && project.designSystem.editableTokens.length > 0) {
    customStyleBlock = `\n  <style>\n    :root {\n`;
    for (const token of project.designSystem.editableTokens) {
      const key = token.replace('.', '_');
      customStyleBlock += `      --ghost-custom-${key}: {{@custom.${key}}};\n`;
    }
    customStyleBlock += `    }\n  </style>\n`;
  }

  return `<!DOCTYPE html>
<html lang="{{@site.locale}}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{{meta_title}}</title>
  <link rel="stylesheet" href="{{asset "css/theme.css"}}" />${customStyleBlock}
  {{ghost_head}}
</head>
<body class="{{body_class}}">
  {{{body}}}
  <script src="{{asset "js/theme.js"}}"></script>
  {{ghost_foot}}
</body>
</html>`;
}

function generateJS(): string {
  return `// Ghost Theme JS - Generated by Ghost Theme Builder
(function() {
  // Mobile menu toggle
  const menuToggle = document.querySelector('.menu-toggle');
  const navList = document.querySelector('.nav-list');
  if (menuToggle && navList) {
    menuToggle.addEventListener('click', () => navList.classList.toggle('is-open'));
  }
})();`;
}

function generateHeaderPartial(project: ProjectInput): string {
  return `<header class="site-header">
  <div style="display:flex;align-items:center;gap:12px">
    {{#if @site.logo}}<img src="{{@site.logo}}" alt="{{@site.title}}" style="height:32px" />{{/if}}
    <a href="{{@site.url}}" style="font-size:18px;font-weight:700;color:var(--color-text);text-decoration:none">{{@site.title}}</a>
  </div>
  {{> "navigation"}}
</header>`;
}

function generateFooterPartial(project: ProjectInput): string {
  return `<footer class="site-footer">
  <p style="font-weight:600;margin-bottom:8px">{{@site.title}}</p>
  {{navigation type="secondary"}}
  <p style="font-size:13px;color:var(--color-text-muted);margin-top:16px">&copy; {{date format="YYYY"}} {{@site.title}}. All rights reserved.</p>
</footer>`;
}

function generateNavigationPartial(): string {
  return `<nav class="site-nav">
  <ul class="nav-list">
    {{#foreach navigation}}
    <li class="{{link_class for=(url) class=(concat "nav-" slug)}}"><a href="{{url absolute="true"}}">{{label}}</a></li>
    {{/foreach}}
  </ul>
</nav>`;
}

function generatePostCardPartial(): string {
  return `<article class="post-card {{post_class}}">
  {{#if feature_image}}
  <a href="{{url}}"><img class="post-card-image" src="{{feature_image}}" alt="{{title}}" /></a>
  {{/if}}
  <div class="post-card-content">
    {{#if primary_tag}}<span style="font-size:12px;color:var(--color-primary);font-weight:600">{{primary_tag.name}}</span>{{/if}}
    <h3 style="margin:8px 0"><a href="{{url}}" style="color:var(--color-text)">{{title}}</a></h3>
    <p style="font-size:14px;color:var(--color-text-muted)">{{excerpt words="20"}}</p>
  </div>
</article>`;
}

function generatePageTemplate(page: PageInput, _project: ProjectInput): { path: string; content: string } {
  const html = renderPageContent(page);

  if (page.type === "home" || page.isHomepage) {
    return {
      path: "index.hbs",
      content: `{{!< default}}\n{{!-- Home Page --}}\n${html}`,
    };
  }

  if (page.isCollection) {
    return {
      path: `${page.slug}.hbs`,
      content: `{{!< default}}\n{{!-- Collection: ${page.name} --}}\n${html}`,
    };
  }

  if (page.type === "blog") {
    return {
      path: "index.hbs",
      content: `{{!< default}}\n{{!-- Blog/Post Listing --}}\n${html}`,
    };
  }

  if (page.type === "post") {
    return { path: "post.hbs", content: `{{!< default}}\n${html}` };
  }

  // Custom pages
  return {
    path: `page-${page.slug}.hbs`,
    content: `{{!< default}}\n{{!-- ${page.name} --}}\n${html}`,
  };
}

function generateIndexFallback(): string {
  return `{{!< default}}
<div class="container" style="padding:${80}px 24px">
  <div class="post-feed" style="grid-template-columns:repeat(3,1fr)">
    {{#foreach posts}}
      {{> "post-card"}}
    {{/foreach}}
  </div>
  {{pagination}}
</div>`;
}

function generatePostTemplate(): string {
  return `{{!< default}}
{{#post}}
<article class="post {{post_class}}">
  <header style="text-align:center;padding:60px 24px 40px;max-width:720px;margin:0 auto">
    {{#if primary_tag}}<span style="color:var(--color-primary);font-size:14px;font-weight:600">{{primary_tag.name}}</span>{{/if}}
    <h1 style="margin-top:12px">{{title}}</h1>
    <p style="color:var(--color-text-muted);margin-top:16px">
      <time datetime="{{date format="YYYY-MM-DD"}}">{{date format="D MMMM YYYY"}}</time>
      {{#if primary_author}} · By {{primary_author.name}}{{/if}}
    </p>
  </header>
  {{#if feature_image}}
  <figure style="max-width:960px;margin:0 auto 40px;padding:0 24px">
    <img src="{{feature_image}}" alt="{{title}}" style="width:100%;border-radius:var(--radius)" />
  </figure>
  {{/if}}
  <div class="post-content container" style="max-width:720px">
    {{content}}
  </div>
</article>
{{/post}}`;
}

function generateGenericPageTemplate(): string {
  return `{{!< default}}
{{#post}}
<article class="page {{post_class}}" style="padding:60px 24px;max-width:800px;margin:0 auto">
  <h1>{{title}}</h1>
  <div class="page-content" style="margin-top:24px">
    {{content}}
  </div>
</article>
{{/post}}`;
}

function generateTagTemplate(): string {
  return `{{!< default}}
<div class="container" style="padding:60px 24px">
  {{#tag}}
  <header style="text-align:center;margin-bottom:48px">
    <h1>{{name}}</h1>
    {{#if description}}<p style="color:var(--color-text-muted);margin-top:12px">{{description}}</p>{{/if}}
  </header>
  {{/tag}}
  <div class="post-feed" style="display:grid;grid-template-columns:repeat(3,1fr);gap:24px">
    {{#foreach posts}}
      {{> "post-card"}}
    {{/foreach}}
  </div>
  {{pagination}}
</div>`;
}

function generateAuthorTemplate(): string {
  return `{{!< default}}
<div class="container" style="padding:60px 24px">
  {{#author}}
  <header style="text-align:center;margin-bottom:48px">
    {{#if profile_image}}<img src="{{profile_image}}" alt="{{name}}" style="width:80px;height:80px;border-radius:50%;margin-bottom:16px" />{{/if}}
    <h1>{{name}}</h1>
    {{#if bio}}<p style="color:var(--color-text-muted);margin-top:12px;max-width:480px;margin-left:auto;margin-right:auto">{{bio}}</p>{{/if}}
  </header>
  {{/author}}
  <div class="post-feed" style="display:grid;grid-template-columns:repeat(3,1fr);gap:24px">
    {{#foreach posts}}
      {{> "post-card"}}
    {{/foreach}}
  </div>
  {{pagination}}
</div>`;
}

function generateErrorTemplate(): string {
  return `{{!< default}}
<section style="display:flex;align-items:center;justify-content:center;min-height:60vh;text-align:center;padding:60px 24px">
  <div>
    <h1 style="font-size:72px;font-weight:800;color:var(--color-primary)">{{statusCode}}</h1>
    <p style="font-size:20px;color:var(--color-text-muted);margin-top:16px">{{message}}</p>
    <a href="{{@site.url}}" class="btn-primary" style="margin-top:32px;display:inline-flex">Go Home</a>
  </div>
</section>`;
}
