const fs = require('fs');
const path = require('path');

const categories = [
  'header', 'footer', 'hero', 'posts', 'features', 'cta',
  'recommendations', 'newsletter', 'authors', 'testimonials',
  'tags', 'products', 'stats', 'faq', 'logo-cloud'
];

const layouts = [
  { name: 'Standard', styles: { padding: '32px', textAlign: 'left' } },
  { name: 'Centered', styles: { padding: '48px 32px', textAlign: 'center', alignItems: 'center' } },
  { name: 'Split', styles: { padding: '32px', display: 'flex', gap: '24px' } },
  { name: 'Spacious', styles: { padding: '96px 24px', textAlign: 'center' } },
  { name: 'Compact', styles: { padding: '16px', textAlign: 'left' } }
];

const variants = [
  { prefix: 'Light', colorOverride: { backgroundColor: '#ffffff' } },
  { prefix: 'Dark', colorOverride: { backgroundColor: '#0f172a', color: '#ffffff' } },
  { prefix: 'Brand', colorOverride: { backgroundColor: 'var(--color-primary)', color: '#ffffff' } }
];

const thumbnailFiles = fs.readdirSync(path.join(__dirname, 'public', 'preset-thumbnails'))
  .filter(f => f !== 'placeholder.svg' && f.endsWith('.png'));

// Generate exactly 10 variations per category (combining layouts and variants)
categories.forEach(category => {
  const presets = [];
  let idCounter = 1;
  
  // Find matching predefined thumbnails for this category
  const matchingThumbs = thumbnailFiles.filter(f => f.startsWith(category));
  
  for (let l = 0; l < layouts.length; l++) {
    for (let v = 0; v < variants.length; v++) {
      if (presets.length >= 10) break;
      
      const layout = layouts[l];
      const variant = variants[v];
      const presetId = `${category}-v${idCounter++}`;
      const variantName = `${variant.prefix} ${layout.name}`;
      
      // Select a thumbnail cyclically if any exist, otherwise use placeholder
      const thumb = matchingThumbs.length > 0 
        ? matchingThumbs[(idCounter - 2) % matchingThumbs.length] 
        : 'placeholder.svg';
        
      const presetStr = `{
    id: '${presetId}',
    category: '${category}',
    variantName: '${variantName}',
    keywords: ['${category}', '${variant.prefix.toLowerCase()}', '${layout.name.toLowerCase()}'],
    thumbnailPath: '/preset-thumbnails/${thumb}',
    buildSection: () => ({
      id: \`sec-\${Date.now()}-\${Math.random().toString(36).substring(7)}\`,
      type: '${category}',
      name: '${variantName} ${category.charAt(0).toUpperCase() + category.slice(1)}',
      props: {
        title: { kind: 'static', value: '${variantName} ${category}' },
        subtitle: { kind: 'static', value: 'This is an autogenerated preset for ${category}.' }
      },
      styles: ${JSON.stringify({ ...layout.styles, ...variant.colorOverride })},
      responsiveStyles: {}
    })
  }`;
      presets.push(presetStr);
    }
  }

  const fileContent = `import { SectionPreset } from '../types';

export const ${category.replace(/-([a-z])/g, g => g[1].toUpperCase())}Presets: SectionPreset[] = [
  ${presets.join(',\n  ')}
];
`;

  fs.writeFileSync(
    path.join(__dirname, 'src', 'presetLibrary', 'presets', `${category}.ts`),
    fileContent
  );
});

console.log('Successfully generated 150 components.');
